[workspace]
resolver = "3"
members = ["crates/freyja", "crates/freyja-builder-buildkit","crates/freyja-core", "crates/freyja-extension-altrpm", "crates/freyja-extension-oci"]

[workspace.dependencies]
freyja-core = { path = "crates/freyja-core" }
freyja-extension-oci = { path = "crates/freyja-extension-oci" }
freyja-extension-altrpm = { path = "crates/freyja-extension-altrpm" }
freyja-builder-buildkit = { path = "crates/freyja-builder-buildkit" }
async-trait = "0.1.92"
clap = { version = "4.6.7", features = ["derive"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.20"
toml = "1.1.6"
oci-client = "0.17.0"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "process", "io-util"] }
reqwest = { version = "0.12", default-features = false, features = ["rustls-tls"] }
suppaftp = { version = "12.0.1", features = ["tokio"] }
xz2 = "0.1.7"
