version = "1"
title = "freyja ALT RPM example"

[extensions]
oci.enabled = true
alt_rpm.enabled = true

[targets]

[targets.nginx-alt]
image = "registry.example.com/example_user/nginx"
tags = ["latest"]
arches = ["amd64"]
build.context = "."

[targets.nginx-alt.dependencies.base_image]
type = "oci"
ref = "registry.altlinux.org/sisyphus/base:latest"

[targets.nginx-alt.dependencies.nginx_package]
type = "alt_rpm"
repository = "sisyphus"
arch = "x86_64"
package = "nginx"
