[package]
name = "freyja-extension-deb"
version = "1.0.0"
edition = "2024"

[dependencies]
freyja-core.workspace = true
async-trait.workspace = true
serde.workspace = true
toml.workspace = true
thiserror.workspace = true
tokio.workspace = true
reqwest.workspace = true
xz2.workspace = true
sha2.workspace = true
chrono = "0.4"
