version = "1"
title = "freyja example build spec"

[extensions]
[extensions.oci]
enabled = true

[targets]

[targets.nginx]
image = "registry.example.com/example_user/nginx"
tags = [ "latest" ]
arches = [ "amd64", "arm64" ]

[targets.nginx.build]
context = "."

[targets.nginx.dependencies.base_image]
type = "oci"
reference = "registry.altlinux.org/sisyphus/base"
tag = "latest"
